/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        // konfigurasi database
        String jdbcUrl = "jdbc:mysql://mysql.db.server:3306/my_database?useSSL=false&serverTimezone=UTC";
        String username = "root";
        String password = "root";

        // exception
        try (Connection conn = DriverManager.getConnection(jdbcUrl, username, password)) {
            System.out.println("Koneksi ke database berhasil!");
        } catch (SQLException e) {
            System.err.println("Tidak berhasil Koneksi");
        }
    }

}